version: "3.3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    command: "npm --prefix /usr/src/app run start"
    volumes:
      - "./client:/app"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./server:/var/www"
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
